version: '2'
services:
 
 wp_avasta:
  container_name: wp_avasta
  build : ./wp/ 
  restart: unless-stopped
  environment:
   WORDPRESS_DB_HOST: db_avasta:3306
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_PASSWORD: diemas040492
   WORDPRESS_DB_NAME: avasta
  ports: 
   - "80:80"
   - "443:443"
  links:
   - db_avasta:mysql
  #volumes:
   #- avasta_volume:/var/www/html

 db_avasta:
  container_name: db_avasta
  build: ./db/
  #image: mysql:5.7
  # command: --default-authentication-plugin=mysql_native_password
  restart: unless-stopped
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: diemas040492
   MYSQL_DATABASE: avasta
   MYSQL_USER: avasta
   MYSQL_PASSWORD: avasta_user
  #volumes:
   #- avasta_volume:/var/lib/mysql

#volumes:
 # avasta_volume:
